import { query, internalAction } from "./_generated/server";
import { v } from "convex/values";

/**
 * 🛡️ Daily Sync Cycles
 * 
 * Morning (8:00 AM): Send ONE message per IMPORTANT project family
 * Evening (6:00 PM): Send ONE combined message with ALL projects grouped
 * 
 * Morning: Separate messages per project (focused work)
 * Evening: Single summary message (overview of all pending work)
 * 
 * Discord: Push notifications enabled
 * Telegram: High priority (bypasses mute)
 */

// ============================================
// QUERIES
// ============================================

/**
 * Get combined pending tasks for a project family (parent + subprojects)
 */
export const getProjectFamilyPendingTasks = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const parent = await ctx.db.get(args.projectId);
    if (!parent || parent.isSubproject) return null;

    // Get parent's own tasks
    const parentTasks = await ctx.db
      .query("tasks")
      .withIndex("by_project_completion", (q) =>
        q.eq("projectId", args.projectId).eq("completed", false)
      )
      .order("desc")
      .collect();

    // Get subprojects
    const subprojects = await ctx.db
      .query("projects")
      .withIndex("by_parent", (q) => q.eq("parentProjectId", args.projectId))
      .filter((q) => q.eq(q.field("status"), "active"))
      .collect();

    // Get tasks for each subproject
    const subprojectTasks = await Promise.all(
      subprojects.map(async (sub) => {
        const tasks = await ctx.db
          .query("tasks")
          .withIndex("by_project_completion", (q) =>
            q.eq("projectId", sub._id).eq("completed", false)
          )
          .order("desc")
          .collect();
        return {
          subprojectId: sub._id,
          subprojectName: sub.name.replace(`${parent.name} / `, ""), // Clean name
          tasks: tasks.map((t) => ({
            id: t._id,
            text: t.text,
            autoGenerated: t.autoGenerated,
          })),
          count: tasks.length,
        };
      })
    );

    // Filter out empty subprojects
    const nonEmptySubprojects = subprojectTasks.filter((s) => s.count > 0);

    const totalPending =
      parentTasks.length + nonEmptySubprojects.reduce((sum, s) => sum + s.count, 0);

    return {
      project: {
        id: parent._id,
        name: parent.name,
        group: parent.group,
      },
      parentTasks: parentTasks.map((t) => ({
        id: t._id,
        text: t.text,
        autoGenerated: t.autoGenerated,
      })),
      subprojects: nonEmptySubprojects,
      totalPending,
      hasSubprojects: subprojects.length > 0,
    };
  },
});

/**
 * Get all active parent projects (excluding subprojects)
 */
export const getParentProjects = query({
  args: {
    group: v.optional(v.union(v.literal("important"), v.literal("hobbies"))),
  },
  handler: async (ctx, args) => {
    let query = ctx.db
      .query("projects")
      .withIndex("by_status", (q) => q.eq("status", "active"));

    if (args.group) {
      query = query.filter((q) => q.eq(q.field("group"), args.group));
    }

    const projects = await query.order("desc").collect();

    // Only return parent projects (not subprojects)
    return projects
      .filter((p) => !p.isSubproject)
      .map((p) => ({
        id: p._id,
        name: p.name,
        group: p.group,
      }));
  },
});

/**
 * Get completed tasks count for today across all projects
 * Pass timestamp to bust cache
 */
export const getCompletedTodayCount = query({
  args: { timestamp: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    const startOfDayTimestamp = startOfDay.getTime();

    const completedTasks = await ctx.db
      .query("tasks")
      .withIndex("by_completion", (q) => q.eq("completed", true))
      .collect();

    const todayCompleted = completedTasks.filter(
      (t) => t.completedAt && t.completedAt >= startOfDayTimestamp
    );

    return {
      date: startOfDay.toISOString().split("T")[0],
      totalCompleted: todayCompleted.length,
    };
  },
});

/**
 * Get summary: ALL projects or filtered by group with their pending tasks
 * Pass timestamp to bust cache
 */
export const getEveningSummary = query({
  args: {
    group: v.optional(v.union(v.literal("important"), v.literal("hobbies"))),
    timestamp: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // Get parent projects (filtered by group if specified)
    let allParents = await ctx.db
      .query("projects")
      .withIndex("by_status", (q) => q.eq("status", "active"))
      .collect();

    if (args.group) {
      allParents = allParents.filter((p) => p.group === args.group);
    }

    const parentProjects = allParents.filter((p) => !p.isSubproject);

    const projectSummaries = [];
    let grandTotalPending = 0;

    for (const parent of parentProjects) {
      // Get parent's tasks
      const parentTasks = await ctx.db
        .query("tasks")
        .withIndex("by_project_completion", (q) =>
          q.eq("projectId", parent._id).eq("completed", false)
        )
        .order("desc")
        .collect();

      // Get subprojects and their tasks
      const subprojects = await ctx.db
        .query("projects")
        .withIndex("by_parent", (q) => q.eq("parentProjectId", parent._id))
        .filter((q) => q.eq(q.field("status"), "active"))
        .collect();

      const subprojectData = [];
      for (const sub of subprojects) {
        const tasks = await ctx.db
          .query("tasks")
          .withIndex("by_project_completion", (q) =>
            q.eq("projectId", sub._id).eq("completed", false)
          )
          .order("desc")
          .collect();

        if (tasks.length > 0) {
          subprojectData.push({
            name: sub.name.replace(`${parent.name} / `, ""),
            tasks: tasks.map((t) => t.text),
            count: tasks.length,
          });
        }
      }

      const totalPending = parentTasks.length + subprojectData.reduce((sum, s) => sum + s.count, 0);

      if (totalPending > 0) {
        projectSummaries.push({
          projectName: parent.name,
          group: parent.group,
          parentTasks: parentTasks.map((t) => t.text),
          subprojects: subprojectData,
          totalPending,
          hasSubprojects: subprojects.length > 0,
        });
        grandTotalPending += totalPending;
      }
    }

    // Sort: Important first, then by pending count
    projectSummaries.sort((a, b) => {
      if (a.group === "important" && b.group !== "important") return -1;
      if (a.group !== "important" && b.group === "important") return 1;
      return b.totalPending - a.totalPending;
    });

    return {
      projects: projectSummaries,
      totalProjects: projectSummaries.length,
      grandTotalPending,
    };
  },
});

// ============================================
// CACHE BUSTING
// ============================================
// Queries are cached by default. To ensure fresh data in scheduled actions,
// we pass a timestamp parameter that changes each run, effectively busting the cache.

// ============================================
// MORNING SYNC (8:00 AM) - IMPORTANT ONLY (ONE MESSAGE)
// ============================================

/**
 * Action: Morning sync - send ONE combined message with ALL IMPORTANT projects
 * Uses timestamp to bust query cache and get fresh data
 */
export const morningSyncAllImportant = internalAction({
  args: {},
  handler: async (ctx) => {
    console.log("🌅 Running morning sync - IMPORTANT projects summary...");

    // Use timestamp to bust cache
    const cacheBuster = Date.now();

    // Get summary of IMPORTANT projects with pending tasks
    const summary = await ctx.runQuery(
      // @ts-ignore - internal query
      "daily:getEveningSummary",
      { group: "important", timestamp: cacheBuster }
    );

    const importantProjects = summary.projects;

    if (importantProjects.length === 0) {
      console.log("No important projects with pending tasks");
      return { notified: false, reason: "no_pending_tasks" };
    }

    const totalImportantPending = importantProjects.reduce(
      (sum: number, p: any) => sum + p.totalPending,
      0
    );

    // Build the combined message content
    let content = `🌅 **Morning Sync - Important Projects**\n`;
    content += `📊 **Total Pending:** ${totalImportantPending} tasks across ${importantProjects.length} important projects\n\n`;
    content += `═══════════════════════════════\n\n`;

    for (const proj of importantProjects) {
      content += `🔴 **${proj.projectName}**`;
      if (proj.hasSubprojects) {
        content += ` (with subprojects)`;
      }
      content += ` - ${proj.totalPending} tasks\n`;

      // Parent tasks
      for (const task of proj.parentTasks) {
        content += `  • ${task}\n`;
      }

      // Subproject tasks with prefix
      for (const sub of proj.subprojects) {
        for (const task of sub.tasks) {
          content += `  • [${sub.name}] ${task}\n`;
        }
      }

      content += `\n`;
    }

    content += `═══════════════════════════════\n`;
    content += `💪 *A 1% improvement each time is a big win.*`;

    // Send ONE combined notification
    const result = await ctx.runAction("notifications:broadcastNotification", {
      content,
      mentionUser: true, // Always mention for morning important
      highPriority: true,
      pinMessage: true, // Pin morning important messages
    });

    console.log(`Morning sync completed: ${importantProjects.length} important projects in one message`);
    return {
      notified: true,
      projectsCount: importantProjects.length,
      grandTotalPending: totalImportantPending,
      result,
    };
  },
});

// ============================================
// EVENING SYNC (6:00 PM) - ONE COMBINED MESSAGE
// ============================================

/**
 * Action: Evening sync - send ONE combined message with ALL projects
 * Shows completed tasks today + pending tasks
 * Uses timestamp to bust query cache and get fresh data
 */
export const eveningSyncAllProjects = internalAction({
  args: {},
  handler: async (ctx) => {
    console.log("🌆 Running evening sync - combined summary...");

    // Use timestamp to bust cache
    const cacheBuster = Date.now();

    // Get completed tasks count for today
    const completedStats = await ctx.runQuery(
      // @ts-ignore - internal query
      "daily:getCompletedTodayCount",
      { timestamp: cacheBuster }
    );

    // Get summary of ALL projects with pending tasks
    const summary = await ctx.runQuery(
      // @ts-ignore - internal query
      "daily:getEveningSummary",
      { timestamp: cacheBuster }
    );

    // Build the combined message content
    let content = `🌆 **Evening Sync**\n`;
    content += `✅ **Completed Today:** ${completedStats.totalCompleted} tasks\n`;
    
    if (summary.totalProjects > 0) {
      content += `📊 **Pending:** ${summary.grandTotalPending} tasks across ${summary.totalProjects} projects\n`;
    }
    
    content += `\n`;

    // Only show pending tasks section if there are any
    if (summary.totalProjects > 0) {
      content += `═══════════════════════════════\n\n`;

      for (const proj of summary.projects) {
        const groupEmoji = proj.group === "important" ? "🔴" : "🔵";
        content += `${groupEmoji} **${proj.projectName}**`;
        if (proj.hasSubprojects) {
          content += ` (with subprojects)`;
        }
        content += ` - ${proj.totalPending} tasks\n`;

        // Parent tasks
        for (const task of proj.parentTasks) {
          content += `  • ${task}\n`;
        }

        // Subproject tasks with prefix
        for (const sub of proj.subprojects) {
          for (const task of sub.tasks) {
            content += `  • [${sub.name}] ${task}\n`;
          }
        }

        content += `\n`;
      }

      content += `═══════════════════════════════\n`;
    }
    
    content += `💪 *A 1% improvement each time is a big win.*`;

    // Send ONE combined notification
    const hasImportant = summary.projects.some((p: any) => p.group === "important");
    const hasPending = summary.totalProjects > 0;
    
    const result = await ctx.runAction("notifications:broadcastNotification", {
      content,
      mentionUser: hasImportant && hasPending, // Only mention if important AND pending
      highPriority: hasImportant && hasPending,
      pinMessage: false, // Don't pin evening messages
    });

    console.log(`Evening sync completed: ${completedStats.totalCompleted} completed, ${summary.grandTotalPending} pending`);
    return {
      notified: true,
      completedToday: completedStats.totalCompleted,
      projectsCount: summary.totalProjects,
      grandTotalPending: summary.grandTotalPending,
      result,
    };
  },
});

// ============================================
// UTILITIES
// ============================================

/**
 * Build a flat task list from project family data
 * Format: [Parent Task] or [Subproject / Task]
 */
function buildCombinedTaskList(familyData: any): string[] {
  const tasks: string[] = [];

  // Parent tasks (no prefix)
  for (const task of familyData.parentTasks) {
    tasks.push(task.text);
  }

  // Subproject tasks (with prefix)
  for (const sub of familyData.subprojects) {
    for (const task of sub.tasks) {
      tasks.push(`[${sub.subprojectName}] ${task.text}`);
    }
  }

  return tasks;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ============================================
// SCHEDULED ACTIONS
// ============================================

export const scheduledMorningSync = internalAction({
  args: {},
  handler: async (ctx) => {
    return await ctx.runAction("daily:morningSyncAllImportant", {});
  },
});

export const scheduledEveningSync = internalAction({
  args: {},
  handler: async (ctx) => {
    return await ctx.runAction("daily:eveningSyncAllProjects", {});
  },
});

// ============================================
// LEGACY SUPPORT (Single Project)
// ============================================

export const morningSync = internalAction({
  args: {
    projectId: v.optional(v.id("projects")),
  },
  handler: async (ctx, args) => {
    if (!args.projectId) {
      return await ctx.runAction("daily:morningSyncAllImportant", {});
    }

    const familyData = await ctx.runQuery(
      // @ts-ignore - internal query
      "daily:getProjectFamilyPendingTasks",
      { projectId: args.projectId }
    );

    if (!familyData) {
      return { notified: false, reason: "project_not_found" };
    }

    const allTasks = buildCombinedTaskList(familyData);

    await ctx.runAction("notifications:notifyProjectFamily", {
      projectName: familyData.project.name,
      group: familyData.project.group,
      totalPending: familyData.totalPending,
      tasks: allTasks.slice(0, 20),
      hasSubprojects: familyData.hasSubprojects,
      timeOfDay: "morning",
      isUrgent: true,
    });

    return {
      notified: true,
      project: familyData.project,
      totalPending: familyData.totalPending,
    };
  },
});

// ============================================
// EVENING VICTORY LAP (Legacy - kept for compatibility)
// ============================================

export const getEveningReport = query({
  args: {},
  handler: async (ctx) => {
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    const startOfDayTimestamp = startOfDay.getTime();

    const projects = await ctx.db
      .query("projects")
      .withIndex("by_status", (q) => q.eq("status", "active"))
      .collect();

    const completedTasks = await ctx.db
      .query("tasks")
      .withIndex("by_completion", (q) => q.eq("completed", true))
      .collect();

    const todayCompletions = completedTasks.filter(
      (t) => t.completedAt && t.completedAt >= startOfDayTimestamp
    );

    const byProject = new Map();
    for (const task of todayCompletions) {
      const project = projects.find((p) => p._id === task.projectId);
      if (!project) continue;

      // Use parent name if subproject
      const displayName = project.isSubproject && project.parentProjectId
        ? (await ctx.db.get(project.parentProjectId))?.name || project.name
        : project.name;

      if (!byProject.has(displayName)) {
        byProject.set(displayName, []);
      }
      byProject.get(displayName).push(task.text);
    }

    return {
      date: startOfDay.toISOString().split("T")[0],
      totalCompleted: todayCompletions.length,
      byProject: Array.from(byProject.entries()).map(([name, tasks]) => ({
        projectName: name,
        tasks,
        count: tasks.length,
      })),
    };
  },
});

export const eveningReport = internalAction({
  args: {},
  handler: async (ctx) => {
    const report = await ctx.runQuery(
      // @ts-ignore - internal query
      "daily:getEveningReport",
      {}
    );

    const allTasks = report.byProject.flatMap((p: { tasks: string[] }) => p.tasks);

    await ctx.runAction("notifications:notifyEveningReport", {
      completedCount: report.totalCompleted,
      completedTasks: allTasks.slice(0, 10),
    });

    return {
      notified: true,
      report,
    };
  },
});

// ============================================
// SCHEDULER CONFIGURATION
// ============================================

/**
 * 🕐 Schedule these functions in Convex Dashboard:
 * 
 * JERUSALEM TIME (IST/IDT):
 *   - Winter (Nov-Mar): UTC+2
 *   - Summer (Mar-Oct): UTC+3
 * 
 * MORNING SYNC - 8:00 AM Jerusalem:
 *   - Winter: 6:00 AM UTC → Cron: 0 6 * * *
 *   - Summer: 5:00 AM UTC → Cron: 0 5 * * *
 *   - Function: daily:scheduledMorningSync
 * 
 * EVENING SYNC - 7:00 PM Jerusalem:
 *   - Winter: 5:00 PM UTC → Cron: 0 17 * * *
 *   - Summer: 4:00 PM UTC → Cron: 0 16 * * *
 *   - Function: daily:scheduledEveningSync
 * 
 * RECOMMENDED (Winter Schedule):
 *   Morning: 0 6 * * * (8 AM Jerusalem)
 *   Evening: 0 17 * * * (7 PM Jerusalem)
 * 
 * NOTE: Adjust by 1 hour when daylight saving changes (Mar/Oct)
 */
