import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * 🛡️ Super Todo Schema
 * 
 * Projects: Grouped as "important" (max 3) or "hobbies"
 *   - Parent projects: Main containers (e.g., "DNS-Fabric")
 *   - Subprojects: Linked via parentProjectId (e.g., "Backend", "Frontend")
 * 
 * Tasks: Linked to projects with completion tracking
 * 
 * Daily sync behavior:
 *   - Parent projects: Show ALL tasks (own + all subprojects combined)
 *   - Standalone projects: Show only own tasks
 *   - Subprojects: NOT shown separately (rolled into parent)
 */

export default defineSchema({
  projects: defineTable({
    name: v.string(),
    group: v.union(v.literal("important"), v.literal("hobbies")),
    status: v.union(v.literal("active"), v.literal("archived")),
    lastWorkedOn: v.number(), // timestamp
    parentProjectId: v.optional(v.id("projects")), // null = parent/standalone
    isSubproject: v.optional(v.boolean()), // true = child of parent
  })
    .index("by_group", ["group"])
    .index("by_status", ["status"])
    .index("by_group_status", ["group", "status"])
    .index("by_parent", ["parentProjectId"]), // For fetching subprojects

  tasks: defineTable({
    projectId: v.id("projects"),
    text: v.string(),
    completed: v.boolean(),
    completedAt: v.optional(v.number()),
    autoGenerated: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_project", ["projectId"])
    .index("by_completion", ["completed", "completedAt"])
    .index("by_project_completion", ["projectId", "completed"]),
});
