import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * 🛡️ Super Todo Schema
 * 
 * Projects: Grouped as "important" (max 3) or "hobbies"
 *   - Parent projects: Main containers (e.g., "DNS-Fabric")
 *   - Subprojects: Linked via parentProjectId (e.g., "Backend", "Frontend")
 * 
 * Tasks: Split into two tables for better organization
 *   - inProgressTasks: Active tasks not yet completed
 *   - completedTasks: Tasks that are done (moved here on completion)
 * 
 * Daily sync behavior:
 *   - Parent projects: Show ALL tasks (own + all subprojects combined)
 *   - Standalone projects: Show only own tasks
 *   - Subprojects: NOT shown separately (rolled into parent)
 */

export default defineSchema({
  projects: defineTable({
    name: v.string(),
    group: v.union(v.literal("important"), v.literal("hobbies")),
    status: v.union(v.literal("active"), v.literal("archived")),
    lastWorkedOn: v.number(), // timestamp
    parentProjectId: v.optional(v.id("projects")), // null = parent/standalone
    isSubproject: v.optional(v.boolean()), // true = child of parent
  })
    .index("by_group", ["group"])
    .index("by_status", ["status"])
    .index("by_group_status", ["group", "status"])
    .index("by_parent", ["parentProjectId"]), // For fetching subprojects

  // Active tasks (not completed)
  inProgressTasks: defineTable({
    projectId: v.id("projects"),
    text: v.string(),
    autoGenerated: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_project", ["projectId"])
    .index("by_created", ["createdAt"]),

  // Completed tasks (archived)
  completedTasks: defineTable({
    projectId: v.id("projects"),
    text: v.string(),
    autoGenerated: v.boolean(),
    createdAt: v.number(),
    completedAt: v.number(),
  })
    .index("by_project", ["projectId"])
    .index("by_completed", ["completedAt"])
    .index("by_project_completed", ["projectId", "completedAt"]),
});
