import { query, mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * 🛡️ Task Operations
 * 
 * Queries:
 * - getTasks: Get tasks for a project with filtering
 * - getPendingTasks: Get incomplete tasks
 * - getCompletedToday: Get today's completions
 * 
 * Mutations:
 * - createTask: Add new task
 * - completeTask: Mark complete with timestamp
 * - syncCompletedTasks: AI auto-complete based on conversation text
 */

// ============================================
// QUERIES
// ============================================

/**
 * Get tasks for a project with optional filtering
 */
export const getTasks = query({
  args: {
    projectId: v.id("projects"),
    filter: v.optional(v.union(v.literal("pending"), v.literal("completed"), v.literal("all"))),
  },
  handler: async (ctx, args) => {
    let query = ctx.db
      .query("tasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId));

    const filter = args.filter ?? "all";

    if (filter === "pending") {
      query = query.filter((q) => q.eq(q.field("completed"), false));
    } else if (filter === "completed") {
      query = query.filter((q) => q.eq(q.field("completed"), true));
    }

    const tasks = await query.order("desc").collect();
    return tasks;
  },
});

/**
 * Get pending (incomplete) tasks for a project
 */
export const getPendingTasks = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("tasks")
      .withIndex("by_project_completion", (q) =>
        q.eq("projectId", args.projectId).eq("completed", false)
      )
      .collect();
  },
});

/**
 * Get tasks completed today
 */
export const getCompletedToday = query({
  args: { 
    projectId: v.optional(v.id("projects")) 
  },
  handler: async (ctx, args) => {
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    const startOfDayTimestamp = startOfDay.getTime();

    let query = ctx.db
      .query("tasks")
      .withIndex("by_completion", (q) => q.eq("completed", true));

    // Filter by project if specified
    if (args.projectId) {
      query = query.filter((q) => q.eq(q.field("projectId"), args.projectId));
    }

    const tasks = await query.collect();
    
    // Filter for tasks completed today
    return tasks.filter((task) => 
      task.completedAt && task.completedAt >= startOfDayTimestamp
    );
  },
});

/**
 * Get task count for a project
 */
export const getTaskStats = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const allTasks = await ctx.db
      .query("tasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    const pending = allTasks.filter((t) => !t.completed).length;
    const completed = allTasks.filter((t) => t.completed).length;
    const autoGenerated = allTasks.filter((t) => t.autoGenerated).length;

    return { total: allTasks.length, pending, completed, autoGenerated };
  },
});

// ============================================
// MUTATIONS
// ============================================

/**
 * Create a new task
 */
export const createTask = mutation({
  args: {
    projectId: v.id("projects"),
    text: v.string(),
    autoGenerated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    // Verify project exists
    const project = await ctx.db.get(args.projectId);
    if (!project) {
      throw new Error(`Project not found: ${args.projectId}`);
    }

    const taskId = await ctx.db.insert("tasks", {
      projectId: args.projectId,
      text: args.text,
      completed: false,
      autoGenerated: args.autoGenerated ?? false,
      createdAt: Date.now(),
    });

    // Update project's lastWorkedOn
    await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });

    return { taskId, text: args.text, projectId: args.projectId };
  },
});

/**
 * Mark a task as completed
 */
export const completeTask = mutation({
  args: { taskId: v.id("tasks") },
  handler: async (ctx, args) => {
    const task = await ctx.db.get(args.taskId);
    if (!task) {
      throw new Error(`Task not found: ${args.taskId}`);
    }

    await ctx.db.patch(args.taskId, {
      completed: true,
      completedAt: Date.now(),
    });

    // Update project's lastWorkedOn
    await ctx.db.patch(task.projectId, { lastWorkedOn: Date.now() });

    return { taskId: args.taskId, text: task.text, completed: true };
  },
});

/**
 * Mark a task as incomplete (undo completion)
 */
export const uncompleteTask = mutation({
  args: { taskId: v.id("tasks") },
  handler: async (ctx, args) => {
    const task = await ctx.db.get(args.taskId);
    if (!task) {
      throw new Error(`Task not found: ${args.taskId}`);
    }

    await ctx.db.patch(args.taskId, {
      completed: false,
      completedAt: undefined,
    });

    return { taskId: args.taskId, text: task.text, completed: false };
  },
});

/**
 * Bulk create tasks (for automated task generation)
 */
export const bulkCreateTasks = mutation({
  args: {
    projectId: v.id("projects"),
    tasks: v.array(v.object({
      text: v.string(),
      autoGenerated: v.optional(v.boolean()),
    })),
  },
  handler: async (ctx, args) => {
    const createdTasks = [];

    for (const taskData of args.tasks) {
      const taskId = await ctx.db.insert("tasks", {
        projectId: args.projectId,
        text: taskData.text,
        completed: false,
        autoGenerated: taskData.autoGenerated ?? true,
        createdAt: Date.now(),
      });
      createdTasks.push({ taskId, text: taskData.text });
    }

    // Update project's lastWorkedOn
    await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });

    return { created: createdTasks.length, tasks: createdTasks };
  },
});

// ============================================
// AI AUTO-COMPLETE
// ============================================

/**
 * 🤖 AI Detection & Auto-Complete
 * 
 * Scans conversation text for task completions.
 * If detected text contains task text (case-insensitive), mark as completed.
 */
export const syncCompletedTasks = mutation({
  args: {
    projectId: v.id("projects"),
    detectedText: v.string(),
  },
  handler: async (ctx, args) => {
    // Get pending tasks for this project
    const pendingTasks = await ctx.db
      .query("tasks")
      .withIndex("by_project_completion", (q) =>
        q.eq("projectId", args.projectId).eq("completed", false)
      )
      .collect();

    const completedTasks = [];
    const normalizedInput = args.detectedText.toLowerCase();

    for (const task of pendingTasks) {
      const normalizedTask = task.text.toLowerCase().trim();

      // Check for substring match (simple but effective)
      // Also check for common completion phrases
      const isCompleted =
        normalizedInput.includes(normalizedTask) ||
        normalizedInput.includes(`done with ${normalizedTask}`) ||
        normalizedInput.includes(`finished ${normalizedTask}`) ||
        normalizedInput.includes(`completed ${normalizedTask}`) ||
        normalizedInput.includes(`fixed ${normalizedTask}`) ||
        normalizedInput.includes(`implemented ${normalizedTask}`);

      if (isCompleted) {
        await ctx.db.patch(task._id, {
          completed: true,
          completedAt: Date.now(),
        });
        completedTasks.push({ taskId: task._id, text: task.text });
      }
    }

    // Update project's lastWorkedOn if tasks were completed
    if (completedTasks.length > 0) {
      await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });
    }

    return {
      scanned: pendingTasks.length,
      completed: completedTasks.length,
      tasks: completedTasks,
    };
  },
});
