import { query, mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * 🛡️ Task Operations
 * 
 * Tasks are split between two tables:
 * - inProgressTasks: Active tasks
 * - completedTasks: Completed tasks (moved here on completion)
 */

export const rawCount = query({
  args: {},
  handler: async (ctx: any) => {
    const inProgress = await ctx.db.query("inProgressTasks").collect();
    let oldTasks: any[] = [];
    try { oldTasks = await ctx.db.query("tasks").collect(); } catch (e) {}
    return { 
      inProgress: inProgress.length, 
      oldTasks: oldTasks.length,
      oldPending: oldTasks.filter((t: any) => !t.completed).length,
    };
  },
});

// ============================================
// QUERIES - IN PROGRESS TASKS
// ============================================

/**
 * Get in-progress tasks for a project
 */
export const getTasks = query({
  args: {
    projectId: v.id("projects"),
    filter: v.optional(v.union(v.literal("pending"), v.literal("completed"), v.literal("all"))),
  },
  handler: async (ctx, args) => {
    const filter = args.filter ?? "all";

    let inProgress: any[] = [];
    let completed: any[] = [];

    if (filter === "pending" || filter === "all") {
      inProgress = await ctx.db
        .query("inProgressTasks")
        .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
        .order("desc")
        .collect();
    }

    if (filter === "completed" || filter === "all") {
      completed = await ctx.db
        .query("completedTasks")
        .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
        .order("desc")
        .collect();
    }

    // Combine and format
    const allTasks = [
      ...inProgress.map((t) => ({ ...t, completed: false })),
      ...completed.map((t) => ({ ...t, completed: true })),
    ];

    // Sort by date (newest first)
    allTasks.sort((a, b) => b.createdAt - a.createdAt);

    return allTasks;
  },
});

/**
 * Get pending (in-progress) tasks for a project
 */
export const getPendingTasks = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("inProgressTasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .order("desc")
      .collect();
  },
});

/**
 * Get completed tasks for a project (optionally limited to today)
 */
export const getCompletedTasks = query({
  args: { 
    projectId: v.optional(v.id("projects")),
    todayOnly: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    let query = ctx.db.query("completedTasks");

    if (args.projectId) {
      query = query.withIndex("by_project", (q) => q.eq("projectId", args.projectId));
    }

    const tasks = await query.order("desc").collect();

    if (args.todayOnly) {
      const startOfDay = new Date();
      startOfDay.setHours(0, 0, 0, 0);
      const startOfDayTimestamp = startOfDay.getTime();

      return tasks.filter((t) => t.completedAt >= startOfDayTimestamp);
    }

    return tasks;
  },
});

/**
 * Get completed tasks count for today (across all projects)
 */
export const getCompletedTodayCount = query({
  args: { timestamp: v.optional(v.number()) },
  handler: async (ctx) => {
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    const startOfDayTimestamp = startOfDay.getTime();

    const completedTasks = await ctx.db
      .query("completedTasks")
      .withIndex("by_completed", (q) => q.gte("completedAt", startOfDayTimestamp))
      .collect();

    return {
      date: startOfDay.toISOString().split("T")[0],
      totalCompleted: completedTasks.length,
    };
  },
});

/**
 * Get task stats for a project
 */
export const getTaskStats = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const pending = await ctx.db
      .query("inProgressTasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    const completed = await ctx.db
      .query("completedTasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    const autoGenerated = 
      pending.filter((t) => t.autoGenerated).length +
      completed.filter((t) => t.autoGenerated).length;

    return { 
      total: pending.length + completed.length, 
      pending: pending.length, 
      completed: completed.length, 
      autoGenerated 
    };
  },
});

// ============================================
// MUTATIONS - CREATE & COMPLETE
// ============================================

/**
 * Create a new task (adds to inProgressTasks)
 */
export const createTask = mutation({
  args: {
    projectId: v.id("projects"),
    text: v.string(),
    autoGenerated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    // Verify project exists
    const project = await ctx.db.get(args.projectId);
    if (!project) {
      throw new Error(`Project not found: ${args.projectId}`);
    }

    const taskId = await ctx.db.insert("inProgressTasks", {
      projectId: args.projectId,
      text: args.text,
      autoGenerated: args.autoGenerated ?? false,
      createdAt: Date.now(),
    });

    // Update project's lastWorkedOn
    await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });

    return { taskId, text: args.text, projectId: args.projectId };
  },
});

/**
 * Mark a task as completed (moves from inProgressTasks to completedTasks)
 */
export const completeTask = mutation({
  args: { taskId: v.id("inProgressTasks") },
  handler: async (ctx, args) => {
    const task = await ctx.db.get(args.taskId);
    if (!task) {
      throw new Error(`Task not found: ${args.taskId}`);
    }

    // Create completed task
    const completedTaskId = await ctx.db.insert("completedTasks", {
      projectId: task.projectId,
      text: task.text,
      autoGenerated: task.autoGenerated,
      createdAt: task.createdAt,
      completedAt: Date.now(),
    });

    // Delete from in-progress
    await ctx.db.delete(args.taskId);

    // Update project's lastWorkedOn
    await ctx.db.patch(task.projectId, { lastWorkedOn: Date.now() });

    return { 
      taskId: completedTaskId, 
      originalTaskId: args.taskId,
      text: task.text, 
      completed: true 
    };
  },
});

/**
 * Mark a completed task as incomplete (moves back to inProgressTasks)
 */
export const uncompleteTask = mutation({
  args: { taskId: v.id("completedTasks") },
  handler: async (ctx, args) => {
    const task = await ctx.db.get(args.taskId);
    if (!task) {
      throw new Error(`Completed task not found: ${args.taskId}`);
    }

    // Create in-progress task
    const newTaskId = await ctx.db.insert("inProgressTasks", {
      projectId: task.projectId,
      text: task.text,
      autoGenerated: task.autoGenerated,
      createdAt: task.createdAt,
    });

    // Delete from completed
    await ctx.db.delete(args.taskId);

    return { 
      taskId: newTaskId, 
      originalTaskId: args.taskId,
      text: task.text, 
      completed: false 
    };
  },
});

/**
 * Bulk create tasks (adds to inProgressTasks)
 */
export const bulkCreateTasks = mutation({
  args: {
    projectId: v.id("projects"),
    tasks: v.array(v.object({
      text: v.string(),
      autoGenerated: v.optional(v.boolean()),
    })),
  },
  handler: async (ctx, args) => {
    const createdTasks = [];

    for (const taskData of args.tasks) {
      const taskId = await ctx.db.insert("inProgressTasks", {
        projectId: args.projectId,
        text: taskData.text,
        autoGenerated: taskData.autoGenerated ?? true,
        createdAt: Date.now(),
      });
      createdTasks.push({ taskId, text: taskData.text });
    }

    // Update project's lastWorkedOn
    await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });

    return { created: createdTasks.length, tasks: createdTasks };
  },
});

// ============================================
// AI AUTO-COMPLETE
// ============================================

/**
 * 🤖 AI Detection & Auto-Complete
 * 
 * Scans conversation text for task completions.
 * If detected text contains task text (case-insensitive), mark as completed.
 */
export const syncCompletedTasks = mutation({
  args: {
    projectId: v.id("projects"),
    detectedText: v.string(),
  },
  handler: async (ctx, args) => {
    // Get pending tasks for this project
    const pendingTasks = await ctx.db
      .query("inProgressTasks")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    const completedTasks = [];
    const normalizedInput = args.detectedText.toLowerCase();

    for (const task of pendingTasks) {
      const normalizedTask = task.text.toLowerCase().trim();

      // Check for substring match (simple but effective)
      // Also check for common completion phrases
      const isCompleted =
        normalizedInput.includes(normalizedTask) ||
        normalizedInput.includes(`done with ${normalizedTask}`) ||
        normalizedInput.includes(`finished ${normalizedTask}`) ||
        normalizedInput.includes(`completed ${normalizedTask}`) ||
        normalizedInput.includes(`fixed ${normalizedTask}`) ||
        normalizedInput.includes(`implemented ${normalizedTask}`);

      if (isCompleted) {
        // Move to completed
        await ctx.runMutation("tasks:completeTask", { taskId: task._id });
        completedTasks.push({ taskId: task._id, text: task.text });
      }
    }

    // Update project's lastWorkedOn if tasks were completed
    if (completedTasks.length > 0) {
      await ctx.db.patch(args.projectId, { lastWorkedOn: Date.now() });
    }

    return {
      scanned: pendingTasks.length,
      completed: completedTasks.length,
      tasks: completedTasks,
    };
  },
});

// ============================================
// DATA MIGRATION (for schema changes)
// ============================================

/**
 * Migrate old tasks table to new split tables
 * Run once after schema change
 */
export const migrateOldTasks = mutation({
  args: { confirm: v.boolean() },
  handler: async (ctx, args) => {
    if (!args.confirm) {
      return { migrated: 0, message: "Set confirm: true to migrate" };
    }

    // This would be used if there was an old "tasks" table
    // For now, it's a placeholder for future migrations
    return { migrated: 0, message: "No old tasks table to migrate" };
  },
});
