#!/usr/bin/env node
/**
 * 🛡️ Super Todo CLI
 * 
 * Command-line interface for daily sync cycles:
 * - morning: Fetch active tasks
 * - evening: Victory Lap report
 * - projects: List projects
 * - tasks: List tasks for a project
 */

import dotenv from "dotenv";
import { ConvexClient, createClientFromEnv } from "../convex/client.js";

// Load environment variables
dotenv.config();

const USAGE = `
🛡️ Super Todo CLI

Usage:
  super-todo <command> [options]

Commands:
  morning [project-id]     🌅 Morning sync - fetch active tasks
  evening                  🏆 Victory Lap - today's completed tasks
  projects [--group]       📁 List all projects
  tasks <project-id>       📝 List tasks for a project
  add-project <name>       ➕ Create a new project
  add-task <project-id>    ➕ Add a task to a project
  complete <task-id>       ✅ Mark a task as completed
  stats [project-id]       📊 Show project statistics
  help                     Show this help message

Options:
  --group <important|hobbies>  Filter by group
  --filter <pending|completed|all>  Task filter (default: pending)
  --auto                       Mark task as auto-generated

Examples:
  super-todo morning
  super-todo evening
  super-todo projects --group important
  super-todo tasks abc123 --filter pending
  super-todo add-project "My New Project" --group hobbies
  super-todo add-task abc123 "Fix the login bug"
  super-todo complete task_xyz789
`;

// ============================================
// CLI IMPLEMENTATION
// ============================================

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "help" || command === "--help" || command === "-h") {
    console.log(USAGE);
    process.exit(0);
  }

  let client: ConvexClient;
  try {
    client = createClientFromEnv();
  } catch (error) {
    console.error("❌ Error:", error instanceof Error ? error.message : String(error));
    console.error("\nMake sure CONVEX_URL is set in your .env file");
    process.exit(1);
  }

  try {
    switch (command) {
      case "morning":
        await morningSync(client, args[1]);
        break;

      case "evening":
        await eveningReport(client);
        break;

      case "projects":
        await listProjects(client, parseArgs(args).group as "important" | "hobbies" | undefined);
        break;

      case "tasks":
        await listTasks(client, args[1], parseArgs(args).filter as "pending" | "completed" | "all" | undefined);
        break;

      case "add-project":
        await addProject(client, args[1], parseArgs(args).group as "important" | "hobbies" | undefined);
        break;

      case "add-task":
        await addTask(client, args[1], args.slice(2).join(" "), Boolean(parseArgs(args).auto));
        break;

      case "complete":
        await completeTask(client, args[1]);
        break;

      case "stats":
        await showStats(client, args[1]);
        break;

      default:
        console.error(`❌ Unknown command: ${command}`);
        console.log(USAGE);
        process.exit(1);
    }
  } catch (error) {
    console.error("❌ Error:", error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

// ============================================
// COMMAND IMPLEMENTATIONS
// ============================================

async function morningSync(client: ConvexClient, projectId?: string) {
  console.log("🌅 Good morning! Fetching your active projects...\n");

  const result = await client.morningSync(projectId);

  if (!result.notified) {
    console.log("📭 No active important projects found.");
    console.log("💡 Create a project with: super-todo add-project \"My Project\" --group important");
    return;
  }

  console.log(`📁 Active Project: ${result.project?.name} [${result.project?.group.toUpperCase()}]`);
  console.log(`📝 Pending Tasks: ${result.pendingCount}`);
  console.log("\nRemember: A 1% improvement each time is a big win.\n");

  // Show the tasks
  if (result.project?.id) {
    const tasks = await client.getPendingTasks(result.project.id);
    if (tasks.length > 0) {
      console.log("Today's focus areas:\n");
      tasks.forEach((task) => {
        console.log(`  - [ ] ${task.text}${task.autoGenerated ? " 🤖" : ""}`);
      });
    }
  }
}

async function eveningReport(client: ConvexClient) {
  console.log("🏆 Victory Lap - Let's celebrate today's wins!\n");

  const report = await client.getEveningReport();

  if (report.totalCompleted === 0) {
    console.log("📊 No tasks completed today.");
    console.log("🌟 Tomorrow is a new day for 1% improvements!");
    return;
  }

  console.log(`Date: ${report.date}`);
  console.log(`✅ Total Completed: ${report.totalCompleted}\n`);

  for (const project of report.byProject) {
    console.log(`📁 ${project.projectName} (${project.count} tasks)`);
    for (const task of project.tasks) {
      console.log(`   ✓ ${task}`);
    }
    console.log();
  }

  console.log("🎉 Every 1% adds up to 100%");
  console.log("💤 Rest well, tomorrow brings new opportunities!");
}

async function listProjects(client: ConvexClient, group?: "important" | "hobbies") {
  const projects = await client.getProjects(group, false);

  if (projects.length === 0) {
    console.log("📭 No projects found.");
    console.log("💡 Create one with: super-todo add-project \"My Project\"");
    return;
  }

  console.log("📁 Projects:\n");
  
  // Group by importance
  const important = projects.filter((p) => p.group === "important");
  const hobbies = projects.filter((p) => p.group === "hobbies");

  if (important.length > 0) {
    console.log("🎯 IMPORTANT:");
    important.forEach((p) => {
      console.log(`  [${p._id}] ${p.name}`);
      console.log(`      Last worked: ${new Date(p.lastWorkedOn).toLocaleDateString()}`);
    });
    console.log();
  }

  if (hobbies.length > 0) {
    console.log("🎨 HOBBIES:");
    hobbies.forEach((p) => {
      console.log(`  [${p._id}] ${p.name}`);
    });
    console.log();
  }

  // Show summary
  console.log(`📊 Total: ${projects.length} projects (${important.length} important, ${hobbies.length} hobbies)`);
}

async function listTasks(
  client: ConvexClient,
  projectId?: string,
  filter: "pending" | "completed" | "all" = "pending"
) {
  if (!projectId) {
    console.error("❌ Error: project-id is required");
    console.log("Usage: super-todo tasks <project-id> [--filter pending|completed|all]");
    process.exit(1);
  }

  const project = await client.getProjects().then((p) => p.find((proj) => proj._id === projectId));
  const tasks = await client.getTasks(projectId, filter);

  console.log(`📁 ${project?.name ?? "Project"} - ${filter.toUpperCase()} TASKS\n`);

  if (tasks.length === 0) {
    console.log("📭 No tasks found.");
    return;
  }

  tasks.forEach((task) => {
    const checkbox = task.completed ? "[x]" : "[ ]";
    const autoBadge = task.autoGenerated ? " 🤖" : "";
    console.log(`  - ${checkbox} ${task.text}${autoBadge}`);
  });

  console.log(`\nTotal: ${tasks.length} tasks`);
}

async function addProject(
  client: ConvexClient,
  name?: string,
  group?: "important" | "hobbies"
) {
  if (!name) {
    console.error("❌ Error: project name is required");
    console.log("Usage: super-todo add-project \"My Project\" --group <important|hobbies>");
    process.exit(1);
  }

  if (!group) {
    console.error("❌ Error: --group is required");
    console.log("Usage: super-todo add-project \"My Project\" --group <important|hobbies>");
    process.exit(1);
  }

  const result = await client.createProject(name, group);
  console.log(`✅ Created project: "${name}" [${group.toUpperCase()}]`);
  console.log(`   ID: ${result.projectId}`);
  console.log("\n📈 A 1% improvement each time is a big win!");
}

async function addTask(client: ConvexClient, projectId?: string, text?: string, autoGenerated = false) {
  if (!projectId || !text) {
    console.error("❌ Error: project-id and task text are required");
    console.log("Usage: super-todo add-task <project-id> \"Task description\"");
    process.exit(1);
  }

  const result = await client.createTask(projectId, text, autoGenerated);
  console.log(`✅ Added task: "${text}"`);
  console.log(`   ID: ${result.taskId}`);
}

async function completeTask(client: ConvexClient, taskId?: string) {
  if (!taskId) {
    console.error("❌ Error: task-id is required");
    console.log("Usage: super-todo complete <task-id>");
    process.exit(1);
  }

  const result = await client.completeTask(taskId);
  console.log(`✅ Completed: "${result.text}"`);
  console.log("\n🎉 1% win! Keep the momentum going.");
}

async function showStats(client: ConvexClient, projectId?: string) {
  if (projectId) {
    // Single project stats
    const project = await client.getProjects().then((p) => p.find((proj) => proj._id === projectId));
    const stats = await client.getTaskStats(projectId);

    console.log(`📊 ${project?.name ?? "Project"} Statistics\n`);
    console.log(`  Total Tasks: ${stats.total}`);
    console.log(`  Pending:     ${stats.pending}`);
    console.log(`  Completed:   ${stats.completed}`);
    console.log(`  Auto-Gen:    ${stats.autoGenerated}`);
    console.log(`  Progress:    ${stats.total > 0 ? Math.round((stats.completed / stats.total) * 100) : 0}%`);
  } else {
    // All projects stats
    const projects = await client.getProjects();
    console.log("📊 All Projects Statistics\n");

    for (const project of projects) {
      const stats = await client.getTaskStats(project._id);
      const progress = stats.total > 0 ? Math.round((stats.completed / stats.total) * 100) : 0;
      
      console.log(`📁 ${project.name} [${project.group}]`);
      console.log(`   ${stats.completed}/${stats.total} done (${progress}%) - ${stats.pending} pending`);
    }
  }
}

// ============================================
// UTILITIES
// ============================================

function parseArgs(args: string[]): Record<string, string | boolean | undefined> {
  const result: Record<string, string | boolean | undefined> = {};
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const nextArg = args[i + 1];
      
      if (nextArg && !nextArg.startsWith("--")) {
        result[key] = nextArg;
        i++; // Skip the value
      } else {
        result[key] = true;
      }
    } else if (arg.startsWith("-")) {
      const key = arg.slice(1);
      result[key] = true;
    }
  }
  
  return result;
}

// ============================================
// RUN
// ============================================

main();
