/**
 * 🛡️ Convex Client Wrapper
 * 
 * Type-safe client for the MCP server to interact with Convex backend.
 */

import type { Id } from "../../convex/_generated/dataModel.js";

export interface ConvexClientConfig {
  url: string;
  token?: string;
}

export interface Project {
  _id: Id<"projects">;
  _creationTime: number;
  name: string;
  group: "important" | "hobbies";
  status: "active" | "archived";
  lastWorkedOn: number;
}

export interface Task {
  _id: Id<"tasks">;
  _creationTime: number;
  projectId: Id<"projects">;
  text: string;
  completed: boolean;
  completedAt?: number;
  autoGenerated: boolean;
  createdAt: number;
}

export interface TaskStats {
  total: number;
  pending: number;
  completed: number;
  autoGenerated: number;
}

export interface DailyReport {
  date: string;
  totalCompleted: number;
  byProject: Array<{
    projectName: string;
    tasks: string[];
    count: number;
  }>;
}

export class ConvexClient {
  private url: string;
  private token?: string;

  constructor(config: ConvexClientConfig) {
    this.url = config.url;
    this.token = config.token;
  }

  /**
   * Execute a Convex query
   */
  async query<Args, Result>(name: string, args: Args): Promise<Result> {
    const response = await fetch(`${this.url}/api/query`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(this.token && { Authorization: `Bearer ${this.token}` })
      },
      body: JSON.stringify({
        path: name,
        args
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Convex query failed: ${response.status} - ${error}`);
    }

    const data = await response.json() as { result: Result };
    return data.result;
  }

  /**
   * Execute a Convex mutation
   */
  async mutation<Args, Result>(name: string, args: Args): Promise<Result> {
    const response = await fetch(`${this.url}/api/mutation`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(this.token && { Authorization: `Bearer ${this.token}` })
      },
      body: JSON.stringify({
        path: name,
        args
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Convex mutation failed: ${response.status} - ${error}`);
    }

    const responseText = await response.text();
    let data: { status: string; value: Result };
    
    try {
      data = JSON.parse(responseText) as { status: string; value: Result };
    } catch (e) {
      throw new Error(`Failed to parse Convex response: ${responseText}`);
    }
    
    if (data.status !== "success" || !('value' in data)) {
      throw new Error(`Invalid Convex response format: ${JSON.stringify(data)}`);
    }
    
    return data.value;
  }

  /**
   * Execute a Convex action
   */
  async action<Args, Result>(name: string, args: Args): Promise<Result> {
    const response = await fetch(`${this.url}/api/action`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(this.token && { Authorization: `Bearer ${this.token}` })
      },
      body: JSON.stringify({
        path: name,
        args
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Convex action failed: ${response.status} - ${error}`);
    }

    const data = await response.json() as { result: Result };
    return data.result;
  }

  // ============================================
  // PROJECT METHODS
  // ============================================

  async getProjects(group?: "important" | "hobbies", includeArchived = false): Promise<Project[]> {
    return this.query("projects:getProjects", { group, includeArchived });
  }

  async getActiveProjects(group?: "important" | "hobbies"): Promise<Project[]> {
    return this.query("projects:getActiveProjects", { group });
  }

  async getImportantProjectCount(): Promise<number> {
    return this.query("projects:getImportantProjectCount", {});
  }

  async findProjectByName(name: string): Promise<Project | null> {
    return this.query("projects:findProjectByName", { name });
  }

  async createProject(name: string, group: "important" | "hobbies", skipIfExists = true): Promise<{ projectId: Id<"projects">; name: string; group: string; existing?: boolean; message?: string }> {
    return this.mutation("projects:createProject", { name, group, skipIfExists });
  }

  async archiveProject(projectId: string): Promise<{ projectId: Id<"projects">; status: string }> {
    return this.mutation("projects:archiveProject", { projectId: projectId as Id<"projects"> });
  }

  // ============================================
  // TASK METHODS
  // ============================================

  async getTasks(projectId: string, filter?: "pending" | "completed" | "all"): Promise<Task[]> {
    return this.query("tasks:getTasks", { projectId: projectId as Id<"projects">, filter });
  }

  async getPendingTasks(projectId: string): Promise<Task[]> {
    return this.query("tasks:getPendingTasks", { projectId: projectId as Id<"projects"> });
  }

  async getCompletedToday(projectId?: string): Promise<Task[]> {
    return this.query("tasks:getCompletedToday", { projectId: projectId as Id<"projects"> | undefined });
  }

  async getTaskStats(projectId: string): Promise<TaskStats> {
    return this.query("tasks:getTaskStats", { projectId: projectId as Id<"projects"> });
  }

  async createTask(projectId: string, text: string, autoGenerated = false): Promise<{ taskId: Id<"tasks">; text: string; projectId: Id<"projects"> }> {
    return this.mutation("tasks:createTask", { projectId: projectId as Id<"projects">, text, autoGenerated });
  }

  async completeTask(taskId: string): Promise<{ taskId: Id<"tasks">; text: string; completed: boolean }> {
    return this.mutation("tasks:completeTask", { taskId: taskId as Id<"tasks"> });
  }

  async syncCompletedTasks(projectId: string, detectedText: string): Promise<{ scanned: number; completed: number; tasks: Array<{ taskId: Id<"tasks">; text: string }> }> {
    return this.mutation("tasks:syncCompletedTasks", { projectId: projectId as Id<"projects">, detectedText });
  }

  async bulkCreateTasks(projectId: string, tasks: Array<{ text: string; autoGenerated?: boolean }>): Promise<{ created: number; tasks: Array<{ taskId: Id<"tasks">; text: string }> }> {
    return this.mutation("tasks:bulkCreateTasks", { projectId: projectId as Id<"projects">, tasks });
  }

  // ============================================
  // DAILY REPORT METHODS
  // ============================================

  async getEveningReport(): Promise<DailyReport> {
    return this.query("daily:getEveningReport", {});
  }

  async eveningReport(): Promise<{ notified: boolean; report: DailyReport }> {
    return this.action("daily:eveningReport", {});
  }

  async morningSync(projectId?: string): Promise<{ notified: boolean; project?: { id: Id<"projects">; name: string; group: string }; pendingCount?: number; reason?: string }> {
    return this.action("daily:morningSync", { projectId: projectId as Id<"projects"> | undefined });
  }
}

/**
 * Create Convex client from environment
 * CONVEX_URL can be set in .env file or passed directly
 */
export function createClientFromEnv(): ConvexClient {
  const url = process.env.CONVEX_URL;
  if (!url) {
    throw new Error(
      "CONVEX_URL environment variable is required.\n" +
      "Set it in your .env file or environment.\n" +
      "Get it from your Convex dashboard: https://dashboard.convex.dev"
    );
  }
  
  return new ConvexClient({
    url,
    token: process.env.CONVEX_DEPLOY_KEY
  });
}
