import { z } from "zod";

/**
 * 🛡️ Super Todo MCP Tools
 * 
 * All tool definitions for the MCP server.
 * Tools map to Convex queries, mutations, and actions.
 */

// ============================================
// TOOL DEFINITIONS
// ============================================

export const tools = [
  {
    name: "get_projects",
    description: "Get all projects, optionally filtered by group (important/hobbies). Returns active projects with their task counts.",
    inputSchema: {
      type: "object" as const,
      properties: {
        group: {
          type: "string",
          enum: ["important", "hobbies"],
          description: "Filter by project group (optional)"
        },
        includeArchived: {
          type: "boolean",
          description: "Include archived projects (default: false)"
        }
      }
    }
  },
  {
    name: "add_project",
    description: "Create a new project. If group is not specified, you MUST ask the user 'Is this [IMPORTANT] or [HOBBIES]?' before creating. The name can be auto-detected from the current working directory or conversation context.",
    inputSchema: {
      type: "object" as const,
      properties: {
        name: {
          type: "string",
          description: "Project name - auto-detect from context if not provided"
        },
        group: {
          type: "string",
          enum: ["important", "hobbies"],
          description: "Project group - ASK USER if not specified!"
        },
        autoGenerateTasks: {
          type: "boolean",
          description: "Whether to auto-generate tasks from project context (default: true)"
        }
      },
      required: ["name"]
    }
  },
  {
    name: "detect_project_context",
    description: "🔍 Auto-detect project information from the current working directory. Reads README.md, package.json, Cargo.toml, and other project files to determine project name, description, and potential tasks.",
    inputSchema: {
      type: "object" as const,
      properties: {
        workspacePath: {
          type: "string",
          description: "Path to the workspace/project directory (default: current working directory)"
        }
      }
    }
  },
  {
    name: "archive_project",
    description: "Archive a project (soft delete). You can reactivate it later.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project to archive"
        }
      },
      required: ["projectId"]
    }
  },
  {
    name: "remove_project",
    description: "PERMANENTLY DELETE a project and ALL its tasks (both pending and completed). This action CANNOT be undone!",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project to permanently delete"
        },
        confirm: {
          type: "boolean",
          description: "Set to true to confirm permanent deletion"
        }
      },
      required: ["projectId"]
    }
  },
  {
    name: "clear_project_tasks",
    description: "Delete ALL tasks (pending and completed) for a specific project. The project itself remains. This action CANNOT be undone!",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project whose tasks will be deleted"
        },
        confirm: {
          type: "boolean",
          description: "Set to true to confirm deletion of all tasks"
        }
      },
      required: ["projectId"]
    }
  },
  {
    name: "remove_duplicate_tasks",
    description: "Find and remove duplicate tasks (same text for same project) from inProgressTasks table. Keeps one copy of each duplicate.",
    inputSchema: {
      type: "object" as const,
      properties: {
        dryRun: {
          type: "boolean",
          description: "If true, only show duplicates without deleting them"
        }
      }
    }
  },
  {
    name: "get_tasks",
    description: "Get tasks for a project with filtering. Shows pending, completed, or all tasks.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project"
        },
        filter: {
          type: "string",
          enum: ["pending", "completed", "all"],
          description: "Filter tasks (default: pending)"
        }
      },
      required: ["projectId"]
    }
  },
  {
    name: "add_task",
    description: "Add a task to a project. Use autoGenerated=true for AI-created tasks.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project"
        },
        text: {
          type: "string",
          description: "Task description"
        },
        autoGenerated: {
          type: "boolean",
          description: "Whether this task was auto-generated by AI (default: false)"
        }
      },
      required: ["projectId", "text"]
    }
  },
  {
    name: "complete_task",
    description: "Mark a task as completed manually.",
    inputSchema: {
      type: "object" as const,
      properties: {
        taskId: {
          type: "string",
          description: "ID of the task to complete"
        }
      },
      required: ["taskId"]
    }
  },
  {
    name: "sync_completed_tasks",
    description: "🤖 AI Auto-Complete: Scan conversation text and mark matching tasks as completed. Detects phrases like 'done with', 'finished', 'completed', 'fixed', 'implemented'. Call this automatically when user mentions completing work.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project to scan"
        },
        detectedText: {
          type: "string",
          description: "User message to scan for task completions (e.g., 'I fixed the login bug')"
        }
      },
      required: ["projectId", "detectedText"]
    }
  },
  {
    name: "bulk_add_tasks",
    description: "Add multiple tasks at once. Useful for automated task generation.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project"
        },
        tasks: {
          type: "array",
          items: {
            type: "object",
            properties: {
              text: { type: "string" },
              autoGenerated: { type: "boolean" }
            },
            required: ["text"]
          },
          description: "Array of task objects to create"
        }
      },
      required: ["projectId", "tasks"]
    }
  },
  {
    name: "daily_report",
    description: "🏆 Victory Lap: Generate report of tasks completed today across all projects or a specific project.",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "Optional: specific project ID (default: all projects)"
        }
      }
    }
  },
  {
    name: "get_project_stats",
    description: "Get task statistics for a project (total, pending, completed, auto-generated).",
    inputSchema: {
      type: "object" as const,
      properties: {
        projectId: {
          type: "string",
          description: "ID of the project"
        }
      },
      required: ["projectId"]
    }
  }
];

// ============================================
// VALIDATION SCHEMAS
// ============================================

export const GetProjectsSchema = z.object({
  group: z.enum(["important", "hobbies"]).optional(),
  includeArchived: z.boolean().optional()
});

export const AddProjectSchema = z.object({
  name: z.string(),
  group: z.enum(["important", "hobbies"]).optional(),
  autoGenerateTasks: z.boolean().optional()
});

export const DetectProjectContextSchema = z.object({
  workspacePath: z.string().optional()
});

export const ArchiveProjectSchema = z.object({
  projectId: z.string()
});

export const GetTasksSchema = z.object({
  projectId: z.string(),
  filter: z.enum(["pending", "completed", "all"]).optional()
});

export const AddTaskSchema = z.object({
  projectId: z.string(),
  text: z.string(),
  autoGenerated: z.boolean().optional()
});

export const CompleteTaskSchema = z.object({
  taskId: z.string()
});

export const SyncCompletedTasksSchema = z.object({
  projectId: z.string(),
  detectedText: z.string()
});

export const BulkAddTasksSchema = z.object({
  projectId: z.string(),
  tasks: z.array(z.object({
    text: z.string(),
    autoGenerated: z.boolean().optional()
  }))
});

export const DailyReportSchema = z.object({
  projectId: z.string().optional()
});

export const GetProjectStatsSchema = z.object({
  projectId: z.string()
});

// ============================================
// TYPE EXPORTS
// ============================================

export type ToolName = 
  | "get_projects"
  | "add_project"
  | "detect_project_context"
  | "archive_project"
  | "remove_project"
  | "clear_project_tasks"
  | "remove_duplicate_tasks"
  | "get_tasks"
  | "add_task"
  | "complete_task"
  | "sync_completed_tasks"
  | "bulk_add_tasks"
  | "daily_report"
  | "get_project_stats";

export type ToolInput =
  | z.infer<typeof GetProjectsSchema>
  | z.infer<typeof AddProjectSchema>
  | z.infer<typeof DetectProjectContextSchema>
  | z.infer<typeof ArchiveProjectSchema>
  | z.infer<typeof GetTasksSchema>
  | z.infer<typeof AddTaskSchema>
  | z.infer<typeof CompleteTaskSchema>
  | z.infer<typeof SyncCompletedTasksSchema>
  | z.infer<typeof BulkAddTasksSchema>
  | z.infer<typeof DailyReportSchema>
  | z.infer<typeof GetProjectStatsSchema>;
